### ISSUE TITLE
[Bug]: Can't get the content data

### ISSUE THREAD

**Issue by gmanikandan-dev** [InfinityXTech/filament-unlayer#2]
### What happened?

I just used the below code in the form.The validation error shows after I updated the content. Could you help me to fix this?

`Unlayer::make('content')->required()`

![issue-content](https://github.com/user-attachments/assets/fdddf791-2d90-4458-80cd-060416a80538)

Thank you!

### How to reproduce the bug

I've followed installation and usage of your Readme file.

### Package Version

3.0.62

### PHP Version

8.2.23

### Laravel Version

10.48.20

### Which operating systems does with happen with?

Linux

**Comment by InfinityXTech** [comment]
Can you give me a repo with full code example? Because I just tried on latest filament fresh app and it is working.

**Comment by gmanikandan-dev** [comment]
[https://github.com/gmanikandan-dev/filament-unlayer](url) 

Model => **app/Models/Template.php**
Filamentphp => **app/Filament/Resources/TemplateResource.php**

You may use the master branch of this repo. I'm just using TemplateResource.php file. It has title,description and content.

Thank you!

**Comment by InfinityXTech** [comment]
Sorry, I was on a small vacation, it will be fixed in a next release in a day.

**Comment by gmanikandan-dev** [comment]
I'm waiting for your next release :)

**Comment by gmanikandan-dev** [comment]
Yes, Now It's work fine.
Thank you for fixing this issue @InfinityXTech .
